package com.tsdm.agent;

public interface dmDefineMsg
{
	int TASK_MSG_OS_INITIALIZED = 0;
	int TASK_MSG_PHONEBOOK_INITIALIZED = 1;
	int TASK_MSG_NETWORK_STATUS_UPDATED = 2;
	int TASK_MSG_DM_SYNCML_CONNECT = 11;
	int TASK_MSG_DM_SYNCML_INIT = 12;
	int TASK_MSG_DM_SYNCML_IDLE_STATE = 13;

	// DM TASK //
	int TASK_MSG_DM_SYNCML_CONNECTFAIL = 21;
	int TASK_MSG_DM_SYNCML_CONNECTRETRY = 22;
	int TASK_MSG_DM_SYNCML_START = 23;
	int TASK_MSG_DM_SYNCML_CONTINUE = 24;
	int TASK_DM_SYNCML_ABORT = 25;
	int TASK_MSG_DM_SYNCML_FINISH = 26;
	int TASK_MSG_DM_SYNCML_SENDFAIL = 27;
	int TASK_MSG_DM_SYNCML_RECEIVEFAIL = 28;
	int TASK_MSG_DM_OBEX_DEVICE_ACTIVATE = 29;
	int TASK_MSG_DM_OBEX_DATA_RECEIVED = 30;
	int TASK_MSG_DM_OBEX_DEVICE_DEACTIVATE = 31;

	int TASK_MSG_DM_TCPIP_OPEN = 32;
	int TASK_MSG_DM_TCPIP_SEND = 33;
	int TASK_MSG_DM_TCPIP_CLOSE = 34;
	int TASK_MSG_DM_SOCKET_CONNECTED = 35;
	int TASK_MSG_DM_SOCKET_DISCONNECTED = 36;
	int TASK_MSG_DM_SOCKET_DATA_RECEIVED = 37;
	int TASK_MSG_DM_SOCKET_SSL_TUNNEL_CONNECT = 38;
	int TASK_MSG_DM_TCPAPN_OPEN = 39;

	int TASK_MSG_DM_DDF_PARSER_ACTIVE = 61;
	int TASK_MSG_DM_DDF_PARSER_PROCESS = 62;

	int TASK_MSG_DM_POLLING_UPDATE = 70;
	int TASK_MSG_DM_AUTO_UPDATE_INITIATED = 71;
	
	int TASK_MSG_DM_CLEAR_SESSION = 99;


	// DL TASK //
	int TASK_MSG_DL_SYNCML_CONNECT = 112;
	int TASK_MSG_DL_SYNCML_CONNECTFAIL = 113;
	int TASK_MSG_DL_SYNCML_ABORT = 114;
	int TASK_MSG_DL_SYNCML_CONNECTRETRY = 115;
	int TASK_MSG_DL_SYNCML_START = 116;
	int TASK_MSG_DL_TCPIP_OPEN = 117;
	int TASK_MSG_DL_TCPIP_SEND = 118;
	int TASK_MSG_DL_TCPIP_CLOSE = 119;
	int TASK_MSG_DL_SYNCML_CONTINUE = 120;
	int	TASK_MSG_DL_SOCKET_DATA_RECEIVED			= 121;
	int TASK_MSG_DL_SOCKET_SSL_TUNNEL_CONNECT = 122;
	int TASK_MSG_DL_SYNCML_FINISH = 123;
	int TASK_MSG_DL_SYNCML_SENDFAIL = 124;
	int TASK_MSG_DL_SYNCML_RECEIVEFAIL = 125;
	int TASK_MSG_DL_TCPAPN_OPEN = 126;

	int TASK_MSG_UIC_REQUEST = 128;
	int TASK_MSG_UIC_RESPONSE = 129;

	// for Firmware Update.
	int TASK_MSG_DL_FIRMWARE_UPDATE = 272;
	int TASK_MSG_DL_LOW_BATTERY_BEFORE_DOWNLOAD = 273;
	int TASK_MSG_DL_POSTPONE = 274;
	int TASK_MSG_DL_USER_CANCEL_DOWNLOAD = 275;
	int TASK_MSG_DL_DOWNLOAD_FILE_ERROR = 276;
	int TASK_MSG_DL_USER_SUSPEND = 277;


	int TASK_MSG_DL_FIRMWARE_UPDATE_STANDBY = 279;
	int TASK_MSG_DL_FIRMWARE_UPDATE_START = 280;
	int TASK_MSG_DL_FIRMWARE_UPDATE_SUCCESS = 281;
	int TASK_MSG_DL_FIRMWARE_UPDATE_FAIL    = 282;
	int TASK_MSG_DL_FIRMWARE_UPDATE_USERCANCEL = 283;
	int TASK_MSG_DL_FIRMWARE_UPDATE_PARTITION = 284;

	int	TASK_ABORT_PARSING_FAIL					= 0xFF;
	int	TASK_ABORT_CONNECTION_FAIL				= 0xFE;
	int	TASK_ABORT_SEND_FAIL					= 0xFD;
	int	TASK_ABORT_RECEIVE_FAIL					= 0XFC;
	int TASK_ABORT_USER_REQ 					= 0xFB;
	int	TASK_ABORT_USB_DEACTIVATE				= 0xFA;
	int	TASK_ABORT_HTTP_ERROR					= 0xF9;
	int	TASK_ABORT_OBEX_ERROR					= 0xF8;
	int	TASK_ABORT_AUTH_FAIL					= 0xF7;
	int	TASK_ABORT_INTERNAL_SERVER_ERROR		= 0xF6;
	int TASK_ABORT_SYNCDM_ERROR 				= 0xF5;
	int TASK_ABORT_SYNC_RETRY 					= 0xF4;
	int	TASK_ABORT_SYNC_AIRPLAIN_MODE			= 0xF3;
	int	TASK_ABORT_ALERT_DISPLAY				= 0xF2;
	int	TASK_ABORT_ERROR						= 0xC0;
}
