package com.tsdm.agent;

public interface dmDefineUIEvent
{
	int EVENT_UI_SYNC_START = 101;
	int EVENT_UI_SERVER_CONNECT = 102;
	int DM_EVENT_UI_UIC_REQUEST = 103;
	int DM_EVENT_UI_IN_SYNC = 104;
	int DM_EVENT_UI_NOT_INIT = 105;
	int DM_EVENT_UI_SERVER_CONNECT_FAIL = 106;
	int DM_EVENT_UI_NETWORK_ERR = 107;
	int DM_EVENT_UI_ABORT_BYUSER = 108;
	int DM_EVENT_UI_RECV_FAIL = 109;
	int DM_EVENT_UI_SEND_FAIL = 110;
	int DM_EVENT_UI_HTTP_INTERNAL_ERROR = 111;
	int DM_EVENT_UI_SYNC_ERROR = 112;
	int DM_EVENT_UI_DOWNLOAD_FAIL_RETRY_CONFIRM = 113;
	int DM_EVENT_UI_DOWNLOAD_FAILED_NETWORK_DISCONNECTED = 114;

	int DM_EVENT_UI_NOTI_NOT_SPECIFIED = 121;
	int DM_EVENT_UI_NOTI_BACKGROUND = 122;
	int DM_EVENT_UI_NOTI_INFORMATIVE = 123;
	int DM_EVENT_UI_NOTI_INTERACTIVE = 124;
	int DM_EVENT_UI_IDLE_STATE = 125;
	int DM_EVENT_UI_NOTI_INFORM = 126;
	int DM_EVENT_UI_DOWNLOAD_START_CONFIRM = 127;
	int DM_EVENT_UI_WIFI_DISCONNECTED = 128;
	int DM_EVENT_UI_FDN_ENABLE = 129;
	int DM_EVENT_UI_REMOTE_CLOSED = 130;
	int DM_EVENT_UI_FINISH = 131;

	int DM_UI_BOOTSTRAP_INSTALL = 141;
	int DM_UI_BOOTSTRAP_INSTALL_RETRY = 142;
	int DM_UI_BOOTSTRAP_INSTALL_SUCCESS = 143;
	int DM_UI_BOOTSTRAP_INSTALL_FAIL = 144;

	int DL_EVENT_UI_DOWNLOAD_OPEN_COMMUNICATION = 151;
	int DL_EVENT_UI_DOWNLOAD_YES_NO = 152;
	int DL_EVENT_UI_DOWNLOAD_IN_PROGRESS = 153;
	int DL_EVENT_UI_DOWNLOAD_IN_COMPLETE = 154;
	int DL_EVENT_UI_DM_START_CONFIRM = 155;

	int DL_EVENT_UI_UPDATE_CONFIRM = 160;
	int DL_EVENT_UI_UPDATE_START = 161;
	int DL_EVENT_UI_UPDATE_PRE_START = 162;
	int DL_EVENT_UI_PHONE_REBOOT = 163;
	int DL_EVENT_UI_DOWNLOAD_COMPLETE_SUSPEND = 164;
	int DL_EVENT_UI_DOWNLOAD_COMPLETE_LOW_BATTARY = 165;
	int DL_EVENT_UI_DRAW_DOWNLOAD_PERCENTAGE = 166;
	int DL_EVENT_UI_UPDATE_PLEASE_WAIT = 167;

	int DL_EVNET_UI_UPDATE_SUCCESS = 171;
	int DL_EVENT_UI_UPDATE_FAIL = 172;
	int DL_EVNET_UI_RESUME_DOWNLOAD = 173;
	int DL_EVENT_UI_POSTPONE = 174;
	int DL_EVENT_UI_DOWNLOAD_FAILED_REPORTING = 175;
	int DL_EVENT_UI_USER_CANCEL_REPORTING = 176;
	int DL_EVENT_UI_DOWNLOAD_FAILED = 177;
	int DL_EVENT_UI_DOWNLOAD_IN_CANCEL = 178;
	int DL_EVENT_UI_MEMORY_FULL = 181;
	int DL_EVENT_UI_DELTA_OVER_SIZE = 182;

	int DL_EVENT_UI_ALERT_GARAGE = 183;

}
